services:
  - type: web
    name: tsg-cafe-erp
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: ERP_NAME
        value: Sangat Cafe
      - key: ERP_SUBTITLE
        value: Powered by Trisyns Global
      - key: TIMEZONE
        value: Asia/Karachi
      - key: CURRENCY
        value: PKR
      - key: DATABASE_URL
        fromDatabase:
          name: tsg-cafe-erp-db
          property: connectionString

databases:
  - name: tsg-cafe-erp-db
    databaseName: tsg_cafe_erp
    user: tsg_cafe_user
    region: singapore
    plan: free
